### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by harukakak** [harukakak/protospace-37403#1]
# URL
https://protospace-37403.herokuapp.com/

**Comment by snkw-works** [comment]
@harukakak さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するよう修正しましょう**
一部ユーザーは、ユーザー詳細ページに遷移しようとするとエラー画面に遷移してしまいます。（こちらで作成した「進撃のアーティスト」「テストユーザー2」は正常に遷移することができませんでした。）
<img width="1177" alt="スクリーンショット 2022-01-20 9 43 30" src="https://user-images.githubusercontent.com/54050089/150241699-ec44e233-73a6-4fd9-ba19-d1878fe095f3.png">
<img width="1440" alt="スクリーンショット_2022-01-20_9_35_22" src="https://user-images.githubusercontent.com/54050089/150241708-5d567199-f6e4-4ffa-b68a-b4658d7e744c.png">
<img width="1438" alt="スクリーンショット_2022-01-20_9_36_06" src="https://user-images.githubusercontent.com/54050089/150241715-30a743a9-6648-467b-a788-1bcfb04d90cf.png">

- [ ] **ログアウト状態のユーザーであっても、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページには遷移できるよう修正しましょう**
ログアウト状態のユーザーが「ユーザー詳細ページ」を閲覧できない状態です。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by harukakak** [comment]
二つの挙動に対して正常に動くよう修正いたしました。
ご確認よろしくお願いします。

**Comment by wakazo228** [comment]
@harukakak さん、ご提出ありがとうございます！
正常に動作することが確認できました！ **LGTM**です✨
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう(^^)
